"""API v1 路由聚合"""
from fastapi import APIRouter
from app.api.v1 import auth, agents, models, chat, conversations, skills, workspaces, mcp_servers, discovery, operation_logs, users, mcp_market, skill_market, agent_market, model_market, scanner, updates, collaborations, skill_optimization, mcp_optimization, conversation_enhancement, knowledge, tasks, system_monitor, backup, backup_enhanced, memory, model_templates, batch_install, skill_reuse, mcp_batch, dialogue_enhancement, monitoring, ops

api_router = APIRouter(prefix="/api/v1")

api_router.include_router(auth.router, prefix="/auth", tags=["认证"])
api_router.include_router(agents.router, prefix="/agents", tags=["Agent管理"])
api_router.include_router(models.router, prefix="/models", tags=["模型配置"])
api_router.include_router(chat.router, prefix="/chat", tags=["对话补全"])
api_router.include_router(skills.router, prefix="/skills", tags=["Skill管理"])
api_router.include_router(mcp_servers.router, prefix="/mcp-servers", tags=["MCP Server管理"])
api_router.include_router(conversations.router, prefix="/conversations", tags=["对话历史"])
api_router.include_router(workspaces.router, prefix="/workspaces", tags=["工作区管理"])
api_router.include_router(discovery.router, prefix="/discover", tags=["Agent发现"])
api_router.include_router(operation_logs.router, prefix="/operation-logs", tags=["操作日志"])
api_router.include_router(users.router, prefix="/users", tags=["用户管理"])
api_router.include_router(mcp_market.router, prefix="/mcp/market", tags=["MCP 在线市场"])
api_router.include_router(skill_market.router, tags=["Skill 在线市场"])
api_router.include_router(agent_market.router, tags=["Agent 在线市场"])
api_router.include_router(model_market.router, tags=["模型在线市场"])
api_router.include_router(scanner.router, tags=["组件扫描器"])
api_router.include_router(updates.router, tags=["更新检测"])
api_router.include_router(collaborations.router, tags=["多智能体协作"])
api_router.include_router(skill_optimization.router, tags=["Skill 优化"])
api_router.include_router(mcp_optimization.router, tags=["MCP 优化"])
api_router.include_router(conversation_enhancement.router, tags=["会话增强"])
api_router.include_router(knowledge.router, tags=["知识库"])
api_router.include_router(tasks.router, tags=["任务管理"])
api_router.include_router(system_monitor.router, tags=["系统监控"])
api_router.include_router(backup.router, tags=["备份与恢复"])
api_router.include_router(backup_enhanced.router, tags=["各智能体备份与恢复(增强)"])
api_router.include_router(memory.router, tags=["记忆管理"])
api_router.include_router(model_templates.router, tags=["模型配置模板"])
api_router.include_router(batch_install.router, tags=["批量安装"])
api_router.include_router(skill_reuse.router, tags=["Skill 复用"])
api_router.include_router(mcp_batch.router, tags=["MCP 批量安装"])
api_router.include_router(dialogue_enhancement.router, tags=["对话增强"])
api_router.include_router(monitoring.router, tags=["监控看板"])
api_router.include_router(ops.router, tags=["智能体自动化运维"])
