"""reconcile schema drift to current models

Revision ID: f5879606c97b
Revises: 03a8f0110b15
Create Date: 2026-08-03 23:30:37.562894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5879606c97b'
down_revision: Union[str, None] = '03a8f0110b15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collaboration_agents_task_id'), table_name='collaboration_agents')
    op.drop_table('collaboration_agents')
    op.add_column('agent_health_configs', sa.Column('l1_interval_sec', sa.Integer(), nullable=True))
    op.add_column('agent_health_configs', sa.Column('l2_interval_sec', sa.Integer(), nullable=True))
    op.add_column('agent_health_configs', sa.Column('l3_interval_sec', sa.Integer(), nullable=True))
    op.add_column('agent_health_configs', sa.Column('l4_interval_sec', sa.Integer(), nullable=True))
    op.add_column('agent_health_configs', sa.Column('ready_endpoint', sa.String(length=512), nullable=True))
    op.add_column('agent_health_configs', sa.Column('pid', sa.Integer(), nullable=True))
    op.add_column('agent_health_configs', sa.Column('process_name', sa.String(length=255), nullable=True))
    op.add_column('agent_health_configs', sa.Column('l3_skills', sa.Text(), nullable=True))
    op.add_column('agent_health_configs', sa.Column('l3_mcp_servers', sa.Text(), nullable=True))
    op.add_column('agent_health_configs', sa.Column('l3_model_id', sa.String(length=255), nullable=True))
    op.add_column('agent_health_configs', sa.Column('l4_test_prompt', sa.Text(), nullable=True))
    op.add_column('agent_health_configs', sa.Column('auto_restart_on_l1_fail', sa.Boolean(), nullable=True))
    op.alter_column('agent_health_configs', 'agent_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('agent_health_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_health_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint(op.f('uq_agent_health_configs_agent_id'), 'agent_health_configs', type_='unique')
    op.create_index(op.f('ix_agent_health_configs_agent_id'), 'agent_health_configs', ['agent_id'], unique=True)
    op.drop_column('agent_health_configs', 'check_interval_minutes')
    op.drop_column('agent_health_configs', 'alert_threshold')
    op.create_index(op.f('ix_agent_metrics_agent_id'), 'agent_metrics', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_metrics_recorded_at'), 'agent_metrics', ['recorded_at'], unique=False)
    op.add_column('agents', sa.Column('webhook_url', sa.String(length=500), nullable=True))
    op.drop_index(op.f('ix_agents_created_at'), table_name='agents')
    op.drop_index(op.f('ix_agents_created_by_status'), table_name='agents')
    op.drop_index(op.f('ix_agents_model_provider'), table_name='agents')
    op.drop_index(op.f('ix_agents_workspace_id_status'), table_name='agents')
    op.create_index(op.f('ix_alert_records_agent_id'), 'alert_records', ['agent_id'], unique=False)
    op.create_index(op.f('ix_alert_records_config_id'), 'alert_records', ['config_id'], unique=False)
    op.create_index(op.f('ix_alert_records_fired_at'), 'alert_records', ['fired_at'], unique=False)
    op.create_index(op.f('ix_audit_alerts_alert_type'), 'audit_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_audit_alerts_created_at'), 'audit_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_alerts_operator_id'), 'audit_alerts', ['operator_id'], unique=False)
    op.add_column('audit_archives', sa.Column('archive_key', sa.String(length=255), nullable=True))
    op.add_column('audit_archives', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('audit_archives', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('audit_archives', sa.Column('record_count', sa.Integer(), nullable=True))
    op.alter_column('audit_archives', 'archive_path',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('audit_archives', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_audit_archives_archive_key'), 'audit_archives', ['archive_key'], unique=False)
    op.drop_column('audit_archives', 'archive_date')
    op.drop_column('audit_archives', 'checksum')
    op.drop_column('audit_archives', 'archive_size_bytes')
    op.drop_column('audit_archives', 'original_log_id')
    op.add_column('audit_logs', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('audit_logs', sa.Column('operator_id', sa.String(length=128), nullable=True))
    op.add_column('audit_logs', sa.Column('operator_name', sa.String(length=128), nullable=True))
    op.add_column('audit_logs', sa.Column('operator_ip', sa.String(length=64), nullable=True))
    op.add_column('audit_logs', sa.Column('device_info', sa.String(length=256), nullable=True))
    op.add_column('audit_logs', sa.Column('category', sa.String(length=32), nullable=True))
    op.add_column('audit_logs', sa.Column('action_type', sa.String(length=64), nullable=True))
    op.add_column('audit_logs', sa.Column('target_id', sa.String(length=256), nullable=True))
    op.add_column('audit_logs', sa.Column('details', sa.Text(), nullable=True))
    op.add_column('audit_logs', sa.Column('result', sa.String(length=16), nullable=True))
    op.add_column('audit_logs', sa.Column('failure_reason', sa.String(length=256), nullable=True))
    op.add_column('audit_logs', sa.Column('trace_id', sa.String(length=64), nullable=True))
    op.add_column('audit_logs', sa.Column('partition_date', sa.Date(), nullable=True))
    op.add_column('audit_logs', sa.Column('verified', sa.Boolean(), nullable=True))
    op.add_column('audit_logs', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('audit_logs', 'curr_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_recorded_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id_action'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_workspace_id'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_category'), 'audit_logs', ['category'], unique=False)
    op.create_index(op.f('ix_audit_logs_operator_id'), 'audit_logs', ['operator_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_partition_date'), 'audit_logs', ['partition_date'], unique=False)
    op.create_index(op.f('ix_audit_logs_result'), 'audit_logs', ['result'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_id'), 'audit_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.drop_column('audit_logs', 'user_id')
    op.drop_column('audit_logs', 'resource_type')
    op.drop_column('audit_logs', 'ip_address')
    op.drop_column('audit_logs', 'agent_id')
    op.drop_column('audit_logs', 'action')
    op.drop_column('audit_logs', 'recorded_at')
    op.drop_column('audit_logs', 'detail')
    op.drop_column('audit_logs', 'user_agent')
    op.drop_column('audit_logs', 'workspace_id')
    op.drop_column('audit_logs', 'resource_id')
    op.add_column('audit_rules', sa.Column('rule_name', sa.String(length=128), nullable=False))
    op.add_column('audit_rules', sa.Column('params', sa.Text(), nullable=True))
    op.add_column('audit_rules', sa.Column('severity', sa.String(length=16), nullable=True))
    op.alter_column('audit_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_audit_rules_rule_type'), 'audit_rules', ['rule_type'], unique=False)
    op.drop_column('audit_rules', 'updated_at')
    op.drop_column('audit_rules', 'name')
    op.drop_column('audit_rules', 'condition')
    op.create_index(op.f('ix_backup_event_logs_agent_id'), 'backup_event_logs', ['agent_id'], unique=False)
    op.add_column('backup_policies', sa.Column('agent_id', sa.String(length=255), nullable=True))
    op.add_column('backup_policies', sa.Column('agent_name', sa.String(length=255), nullable=True))
    op.add_column('backup_policies', sa.Column('full_backup_cron', sa.String(length=64), nullable=True))
    op.add_column('backup_policies', sa.Column('incremental_interval_hours', sa.Integer(), nullable=True))
    op.add_column('backup_policies', sa.Column('event_trigger_enabled', sa.Boolean(), nullable=True))
    op.add_column('backup_policies', sa.Column('event_types', sa.Text(), nullable=True))
    op.add_column('backup_policies', sa.Column('encryption_enabled', sa.Boolean(), nullable=True))
    op.add_column('backup_policies', sa.Column('retention_full_count', sa.Integer(), nullable=True))
    op.add_column('backup_policies', sa.Column('retention_incremental_count', sa.Integer(), nullable=True))
    op.add_column('backup_policies', sa.Column('drill_enabled', sa.Boolean(), nullable=True))
    op.add_column('backup_policies', sa.Column('drill_cron', sa.String(length=64), nullable=True))
    op.add_column('backup_policies', sa.Column('default_scope', sa.String(length=32), nullable=True))
    op.alter_column('backup_policies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('backup_policies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_backup_policies_agent_id'), 'backup_policies', ['agent_id'], unique=True)
    op.drop_column('backup_policies', 'workspace_id')
    op.drop_column('backup_policies', 'schedule')
    op.drop_column('backup_policies', 'components')
    op.drop_column('backup_policies', 'name')
    op.add_column('backup_records', sa.Column('agent_id', sa.String(length=255), nullable=True))
    op.add_column('backup_records', sa.Column('agent_name', sa.String(length=255), nullable=True))
    op.add_column('backup_records', sa.Column('scope', sa.String(length=32), nullable=True))
    op.add_column('backup_records', sa.Column('base_backup_id', sa.String(length=255), nullable=True))
    op.add_column('backup_records', sa.Column('checksum_sha256', sa.String(length=128), nullable=True))
    op.add_column('backup_records', sa.Column('encryption_algo', sa.String(length=32), nullable=True))
    op.add_column('backup_records', sa.Column('key_id', sa.String(length=64), nullable=True))
    op.add_column('backup_records', sa.Column('data_stats', sa.Text(), nullable=True))
    op.add_column('backup_records', sa.Column('retained_until', sa.DateTime(), nullable=True))
    op.add_column('backup_records', sa.Column('duration_seconds', sa.Float(), nullable=True))
    op.add_column('backup_records', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('backup_records', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('backup_records', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.alter_column('backup_records', 'backup_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=16),
               existing_nullable=True)
    op.alter_column('backup_records', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=16),
               existing_nullable=True,
               existing_server_default=sa.text("'running'::character varying"))
    op.alter_column('backup_records', 'file_path',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('backup_records', 'size_bytes',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('backup_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('backup_records', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('ix_backup_records_status'), table_name='backup_records')
    op.drop_index(op.f('ix_backup_records_workspace_id'), table_name='backup_records')
    op.create_index(op.f('ix_backup_records_agent_id'), 'backup_records', ['agent_id'], unique=False)
    op.drop_column('backup_records', 'started_at')
    op.drop_column('backup_records', 'checksum')
    op.drop_column('backup_records', 'encrypted')
    op.drop_column('backup_records', 'included_components')
    op.drop_column('backup_records', 'workspace_id')
    op.create_index(op.f('ix_batch_install_items_queue_id'), 'batch_install_items', ['queue_id'], unique=False)
    op.add_column('collaboration_tasks', sa.Column('collaboration_id', sa.String(length=36), nullable=False))
    op.add_column('collaboration_tasks', sa.Column('agent_id', sa.String(length=36), nullable=False))
    op.add_column('collaboration_tasks', sa.Column('agent_name', sa.String(length=200), nullable=True))
    op.add_column('collaboration_tasks', sa.Column('order', sa.Integer(), nullable=True))
    op.add_column('collaboration_tasks', sa.Column('role', sa.String(length=50), nullable=True))
    op.add_column('collaboration_tasks', sa.Column('input_text', sa.Text(), nullable=True))
    op.add_column('collaboration_tasks', sa.Column('output_text', sa.Text(), nullable=True))
    op.add_column('collaboration_tasks', sa.Column('error_message', sa.Text(), nullable=True))
    op.alter_column('collaboration_tasks', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('collaboration_tasks', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('collaboration_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_collaboration_tasks_status'), table_name='collaboration_tasks')
    op.drop_index(op.f('ix_collaboration_tasks_workspace_id'), table_name='collaboration_tasks')
    op.create_index(op.f('ix_collaboration_tasks_collaboration_id'), 'collaboration_tasks', ['collaboration_id'], unique=False)
    op.create_foreign_key(None, 'collaboration_tasks', 'collaborations', ['collaboration_id'], ['id'], ondelete='CASCADE')
    op.drop_column('collaboration_tasks', 'config_json')
    op.drop_column('collaboration_tasks', 'updated_at')
    op.drop_column('collaboration_tasks', 'created_by')
    op.drop_column('collaboration_tasks', 'description')
    op.drop_column('collaboration_tasks', 'progress')
    op.drop_column('collaboration_tasks', 'name')
    op.drop_column('collaboration_tasks', 'goal')
    op.drop_column('collaboration_tasks', 'result_json')
    op.drop_column('collaboration_tasks', 'mode')
    op.drop_column('collaboration_tasks', 'workspace_id')
    op.create_index(op.f('ix_component_scan_items_component_type'), 'component_scan_items', ['component_type'], unique=False)
    op.create_index(op.f('ix_component_scan_items_scan_id'), 'component_scan_items', ['scan_id'], unique=False)
    op.drop_index(op.f('ix_conversations_agent_id_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_user_id_updated_at'), table_name='conversations')
    op.create_index(op.f('ix_dialogue_ratings_conversation_id'), 'dialogue_ratings', ['conversation_id'], unique=False)
    op.add_column('encryption_keys', sa.Column('key_id', sa.String(length=64), nullable=True))
    op.add_column('encryption_keys', sa.Column('status', sa.String(length=16), nullable=True))
    op.add_column('encryption_keys', sa.Column('retired_at', sa.DateTime(), nullable=True))
    op.add_column('encryption_keys', sa.Column('note', sa.String(length=512), nullable=True))
    op.alter_column('encryption_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_encryption_keys_key_name'), 'encryption_keys', type_='unique')
    op.create_unique_constraint(None, 'encryption_keys', ['key_id'])
    op.drop_column('encryption_keys', 'key_name')
    op.drop_column('encryption_keys', 'key_material')
    op.create_index(op.f('ix_heal_rules_agent_id'), 'heal_rules', ['agent_id'], unique=False)
    op.add_column('health_check_runs', sa.Column('agent_name', sa.String(length=255), nullable=True))
    op.add_column('health_check_runs', sa.Column('level', sa.String(length=32), nullable=True))
    op.add_column('health_check_runs', sa.Column('latency_ms', sa.Float(), nullable=True))
    op.add_column('health_check_runs', sa.Column('error_message', sa.Text(), nullable=True))
    op.alter_column('health_check_runs', 'agent_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('health_check_runs', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=16),
               existing_nullable=True)
    op.alter_column('health_check_runs', 'checked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('health_check_runs', 'score')
    op.drop_column('health_check_runs', 'check_level')
    op.create_index(op.f('ix_health_events_agent_id'), 'health_events', ['agent_id'], unique=False)
    op.create_index(op.f('ix_health_events_created_at'), 'health_events', ['created_at'], unique=False)
    op.add_column('health_snapshots', sa.Column('agent_name', sa.String(length=255), nullable=True))
    op.add_column('health_snapshots', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('health_snapshots', sa.Column('score_details', sa.Text(), nullable=True))
    op.add_column('health_snapshots', sa.Column('l1_status', sa.String(length=16), nullable=True))
    op.add_column('health_snapshots', sa.Column('l2_status', sa.String(length=16), nullable=True))
    op.add_column('health_snapshots', sa.Column('l3_status', sa.String(length=16), nullable=True))
    op.add_column('health_snapshots', sa.Column('l4_status', sa.String(length=16), nullable=True))
    op.add_column('health_snapshots', sa.Column('l1_latency', sa.Float(), nullable=True))
    op.add_column('health_snapshots', sa.Column('l2_latency', sa.Float(), nullable=True))
    op.add_column('health_snapshots', sa.Column('l3_latency', sa.Float(), nullable=True))
    op.add_column('health_snapshots', sa.Column('l4_latency', sa.Float(), nullable=True))
    op.add_column('health_snapshots', sa.Column('l3_failed_items', sa.Text(), nullable=True))
    op.add_column('health_snapshots', sa.Column('uptime_seconds', sa.Float(), nullable=True))
    op.add_column('health_snapshots', sa.Column('last_checked_at', sa.DateTime(), nullable=True))
    op.add_column('health_snapshots', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('health_snapshots', 'agent_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('health_snapshots', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.drop_index(op.f('ix_health_snapshots_snapshot_time'), table_name='health_snapshots')
    op.drop_index(op.f('ix_health_snapshots_agent_id'), table_name='health_snapshots')
    op.create_index(op.f('ix_health_snapshots_agent_id'), 'health_snapshots', ['agent_id'], unique=True)
    op.drop_column('health_snapshots', 'overall_score')
    op.drop_column('health_snapshots', 'metrics_json')
    op.drop_column('health_snapshots', 'snapshot_time')
    op.create_index(op.f('ix_health_trend_points_agent_id'), 'health_trend_points', ['agent_id'], unique=False)
    op.create_index(op.f('ix_health_trend_points_bucket_minute'), 'health_trend_points', ['bucket_minute'], unique=False)
    op.create_index(op.f('ix_human_interventions_agent_id'), 'human_interventions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_human_interventions_conversation_id'), 'human_interventions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_document_id'), 'knowledge_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_knowledge_base_id'), 'knowledge_chunks', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_knowledge_base_id'), 'knowledge_documents', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_log_entries_agent_id'), 'log_entries', ['agent_id'], unique=False)
    op.create_index(op.f('ix_log_entries_level'), 'log_entries', ['level'], unique=False)
    op.create_index(op.f('ix_log_entries_timestamp'), 'log_entries', ['timestamp'], unique=False)
    op.create_index(op.f('ix_maintenance_executions_task_id'), 'maintenance_executions', ['task_id'], unique=False)
    op.create_index(op.f('ix_mcp_agent_bindings_agent_id'), 'mcp_agent_bindings', ['agent_id'], unique=False)
    op.create_index(op.f('ix_mcp_agent_bindings_mcp_server_id'), 'mcp_agent_bindings', ['mcp_server_id'], unique=False)
    op.create_index(op.f('ix_mcp_batch_install_items_queue_id'), 'mcp_batch_install_items', ['queue_id'], unique=False)
    op.drop_index(op.f('ix_mcp_servers_health_status'), table_name='mcp_servers')
    op.drop_index(op.f('ix_mcp_servers_name'), table_name='mcp_servers')
    op.drop_index(op.f('ix_mcp_servers_status'), table_name='mcp_servers')
    op.drop_index(op.f('ix_messages_conversation_id_created_at'), table_name='messages')
    op.drop_constraint(op.f('uq_model_cascade_rules_task_type'), 'model_cascade_rules', type_='unique')
    op.drop_index(op.f('ix_model_cascade_rules_task_type'), table_name='model_cascade_rules')
    op.create_index(op.f('ix_model_cascade_rules_task_type'), 'model_cascade_rules', ['task_type'], unique=True)
    op.drop_index(op.f('ix_model_config_templates_created_by'), table_name='model_config_templates')
    op.drop_index(op.f('ix_model_config_templates_provider'), table_name='model_config_templates')
    op.drop_index(op.f('ix_model_config_templates_provider_model'), table_name='model_config_templates')
    op.drop_constraint(op.f('uq_model_template_bindings_template_agent'), 'model_template_bindings', type_='unique')
    op.drop_constraint(op.f('uq_model_template_versions_template_version'), 'model_template_versions', type_='unique')
    op.drop_index(op.f('ix_operation_logs_action'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_resource_type'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_resource_type_resource_id'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_user_id_action'), table_name='operation_logs')
    op.create_index(op.f('ix_restore_drills_agent_id'), 'restore_drills', ['agent_id'], unique=False)
    op.add_column('restore_operations', sa.Column('target_agent_id', sa.String(length=255), nullable=True))
    op.add_column('restore_operations', sa.Column('target_agent_name', sa.String(length=255), nullable=True))
    op.add_column('restore_operations', sa.Column('source_agent_name', sa.String(length=255), nullable=True))
    op.add_column('restore_operations', sa.Column('precheck_result', sa.Text(), nullable=True))
    op.add_column('restore_operations', sa.Column('restored_stats', sa.Text(), nullable=True))
    op.add_column('restore_operations', sa.Column('health_score_after', sa.Float(), nullable=True))
    op.add_column('restore_operations', sa.Column('duration_seconds', sa.Float(), nullable=True))
    op.add_column('restore_operations', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.alter_column('restore_operations', 'backup_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('restore_operations', 'restore_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('restore_operations', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=32),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('restore_operations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('restore_operations', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_restore_operations_backup_id'), 'restore_operations', ['backup_id'], unique=False)
    op.create_index(op.f('ix_restore_operations_target_agent_id'), 'restore_operations', ['target_agent_id'], unique=False)
    op.drop_column('restore_operations', 'started_at')
    op.drop_column('restore_operations', 'workspace_id')
    op.create_index(op.f('ix_scaling_events_agent_id'), 'scaling_events', ['agent_id'], unique=False)
    op.create_index(op.f('ix_scaling_events_created_at'), 'scaling_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_scaling_policies_agent_id'), 'scaling_policies', ['agent_id'], unique=False)
    op.create_index(op.f('ix_scanner_alerts_component_id'), 'scanner_alerts', ['component_id'], unique=False)
    op.create_index(op.f('ix_scanner_alerts_component_type'), 'scanner_alerts', ['component_type'], unique=False)
    op.create_index(op.f('ix_self_heal_records_agent_id'), 'self_heal_records', ['agent_id'], unique=False)
    op.create_index(op.f('ix_self_heal_records_detected_at'), 'self_heal_records', ['detected_at'], unique=False)
    op.alter_column('semantic_cache_entries', 'threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0.92'::double precision"))
    op.alter_column('semantic_cache_entries', 'ttl_seconds',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3600'))
    op.alter_column('semantic_cache_entries', 'hit_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('semantic_cache_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_skill_bindings_enabled'), table_name='skill_bindings')
    op.drop_constraint(op.f('uq_skill_bindings_agent_skill'), 'skill_bindings', type_='unique')
    op.create_index(op.f('ix_skill_reuse_relations_source_skill_id'), 'skill_reuse_relations', ['source_skill_id'], unique=False)
    op.create_index(op.f('ix_skill_reuse_relations_target_agent_id'), 'skill_reuse_relations', ['target_agent_id'], unique=False)
    op.create_index(op.f('ix_skill_reuse_relations_target_skill_id'), 'skill_reuse_relations', ['target_skill_id'], unique=False)
    op.drop_index(op.f('ix_skills_category'), table_name='skills')
    op.drop_index(op.f('ix_skills_enabled'), table_name='skills')
    op.drop_index(op.f('ix_skills_type'), table_name='skills')
    op.drop_constraint(op.f('uq_skills_name_version'), 'skills', type_='unique')
    op.alter_column('token_budgets', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_constraint(op.f('uq_token_budgets_user_id'), 'token_budgets', type_='unique')
    op.drop_index(op.f('ix_token_budgets_user_id'), table_name='token_budgets')
    op.create_index(op.f('ix_token_budgets_user_id'), 'token_budgets', ['user_id'], unique=True)
    op.create_index(op.f('ix_update_logs_component_id'), 'update_logs', ['component_id'], unique=False)
    op.create_index(op.f('ix_update_logs_component_type'), 'update_logs', ['component_type'], unique=False)
    op.create_index(op.f('ix_update_snapshots_component_id'), 'update_snapshots', ['component_id'], unique=False)
    op.create_index(op.f('ix_update_snapshots_component_type'), 'update_snapshots', ['component_type'], unique=False)
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_workspace_members_workspace_id_role'), table_name='workspace_members')
    op.drop_constraint(op.f('uq_workspace_members'), 'workspace_members', type_='unique')
    op.drop_index(op.f('ix_workspaces_is_active'), table_name='workspaces')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_workspaces_is_active'), 'workspaces', ['is_active'], unique=False)
    op.create_unique_constraint(op.f('uq_workspace_members'), 'workspace_members', ['workspace_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_workspace_members_workspace_id_role'), 'workspace_members', ['workspace_id', 'role'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.drop_index(op.f('ix_update_snapshots_component_type'), table_name='update_snapshots')
    op.drop_index(op.f('ix_update_snapshots_component_id'), table_name='update_snapshots')
    op.drop_index(op.f('ix_update_logs_component_type'), table_name='update_logs')
    op.drop_index(op.f('ix_update_logs_component_id'), table_name='update_logs')
    op.drop_index(op.f('ix_token_budgets_user_id'), table_name='token_budgets')
    op.create_index(op.f('ix_token_budgets_user_id'), 'token_budgets', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('uq_token_budgets_user_id'), 'token_budgets', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('token_budgets', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.create_unique_constraint(op.f('uq_skills_name_version'), 'skills', ['name', 'version'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_skills_type'), 'skills', ['type'], unique=False)
    op.create_index(op.f('ix_skills_enabled'), 'skills', ['enabled'], unique=False)
    op.create_index(op.f('ix_skills_category'), 'skills', ['category'], unique=False)
    op.drop_index(op.f('ix_skill_reuse_relations_target_skill_id'), table_name='skill_reuse_relations')
    op.drop_index(op.f('ix_skill_reuse_relations_target_agent_id'), table_name='skill_reuse_relations')
    op.drop_index(op.f('ix_skill_reuse_relations_source_skill_id'), table_name='skill_reuse_relations')
    op.create_unique_constraint(op.f('uq_skill_bindings_agent_skill'), 'skill_bindings', ['agent_id', 'skill_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_skill_bindings_enabled'), 'skill_bindings', ['enabled'], unique=False)
    op.alter_column('semantic_cache_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('semantic_cache_entries', 'hit_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('semantic_cache_entries', 'ttl_seconds',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3600'))
    op.alter_column('semantic_cache_entries', 'threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0.92'::double precision"))
    op.drop_index(op.f('ix_self_heal_records_detected_at'), table_name='self_heal_records')
    op.drop_index(op.f('ix_self_heal_records_agent_id'), table_name='self_heal_records')
    op.drop_index(op.f('ix_scanner_alerts_component_type'), table_name='scanner_alerts')
    op.drop_index(op.f('ix_scanner_alerts_component_id'), table_name='scanner_alerts')
    op.drop_index(op.f('ix_scaling_policies_agent_id'), table_name='scaling_policies')
    op.drop_index(op.f('ix_scaling_events_created_at'), table_name='scaling_events')
    op.drop_index(op.f('ix_scaling_events_agent_id'), table_name='scaling_events')
    op.add_column('restore_operations', sa.Column('workspace_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('restore_operations', sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_restore_operations_target_agent_id'), table_name='restore_operations')
    op.drop_index(op.f('ix_restore_operations_backup_id'), table_name='restore_operations')
    op.alter_column('restore_operations', 'completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('restore_operations', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('restore_operations', 'status',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('restore_operations', 'restore_type',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('restore_operations', 'backup_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.drop_column('restore_operations', 'created_by')
    op.drop_column('restore_operations', 'duration_seconds')
    op.drop_column('restore_operations', 'health_score_after')
    op.drop_column('restore_operations', 'restored_stats')
    op.drop_column('restore_operations', 'precheck_result')
    op.drop_column('restore_operations', 'source_agent_name')
    op.drop_column('restore_operations', 'target_agent_name')
    op.drop_column('restore_operations', 'target_agent_id')
    op.drop_index(op.f('ix_restore_drills_agent_id'), table_name='restore_drills')
    op.create_index(op.f('ix_operation_logs_user_id_action'), 'operation_logs', ['user_id', 'action'], unique=False)
    op.create_index(op.f('ix_operation_logs_resource_type_resource_id'), 'operation_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_operation_logs_resource_type'), 'operation_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_operation_logs_action'), 'operation_logs', ['action'], unique=False)
    op.create_unique_constraint(op.f('uq_model_template_versions_template_version'), 'model_template_versions', ['template_id', 'version'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_model_template_bindings_template_agent'), 'model_template_bindings', ['template_id', 'agent_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_model_config_templates_provider_model'), 'model_config_templates', ['provider', 'model'], unique=False)
    op.create_index(op.f('ix_model_config_templates_provider'), 'model_config_templates', ['provider'], unique=False)
    op.create_index(op.f('ix_model_config_templates_created_by'), 'model_config_templates', ['created_by'], unique=False)
    op.drop_index(op.f('ix_model_cascade_rules_task_type'), table_name='model_cascade_rules')
    op.create_index(op.f('ix_model_cascade_rules_task_type'), 'model_cascade_rules', ['task_type'], unique=False)
    op.create_unique_constraint(op.f('uq_model_cascade_rules_task_type'), 'model_cascade_rules', ['task_type'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_messages_conversation_id_created_at'), 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_mcp_servers_status'), 'mcp_servers', ['status'], unique=False)
    op.create_index(op.f('ix_mcp_servers_name'), 'mcp_servers', ['name'], unique=False)
    op.create_index(op.f('ix_mcp_servers_health_status'), 'mcp_servers', ['health_status'], unique=False)
    op.drop_index(op.f('ix_mcp_batch_install_items_queue_id'), table_name='mcp_batch_install_items')
    op.drop_index(op.f('ix_mcp_agent_bindings_mcp_server_id'), table_name='mcp_agent_bindings')
    op.drop_index(op.f('ix_mcp_agent_bindings_agent_id'), table_name='mcp_agent_bindings')
    op.drop_index(op.f('ix_maintenance_executions_task_id'), table_name='maintenance_executions')
    op.drop_index(op.f('ix_log_entries_timestamp'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_level'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_agent_id'), table_name='log_entries')
    op.drop_index(op.f('ix_knowledge_documents_knowledge_base_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_chunks_knowledge_base_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_document_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_human_interventions_conversation_id'), table_name='human_interventions')
    op.drop_index(op.f('ix_human_interventions_agent_id'), table_name='human_interventions')
    op.drop_index(op.f('ix_health_trend_points_bucket_minute'), table_name='health_trend_points')
    op.drop_index(op.f('ix_health_trend_points_agent_id'), table_name='health_trend_points')
    op.add_column('health_snapshots', sa.Column('snapshot_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('health_snapshots', sa.Column('metrics_json', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('health_snapshots', sa.Column('overall_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_health_snapshots_agent_id'), table_name='health_snapshots')
    op.create_index(op.f('ix_health_snapshots_agent_id'), 'health_snapshots', ['agent_id'], unique=False)
    op.create_index(op.f('ix_health_snapshots_snapshot_time'), 'health_snapshots', ['snapshot_time'], unique=False)
    op.alter_column('health_snapshots', 'status',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('health_snapshots', 'agent_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.drop_column('health_snapshots', 'created_at')
    op.drop_column('health_snapshots', 'last_checked_at')
    op.drop_column('health_snapshots', 'uptime_seconds')
    op.drop_column('health_snapshots', 'l3_failed_items')
    op.drop_column('health_snapshots', 'l4_latency')
    op.drop_column('health_snapshots', 'l3_latency')
    op.drop_column('health_snapshots', 'l2_latency')
    op.drop_column('health_snapshots', 'l1_latency')
    op.drop_column('health_snapshots', 'l4_status')
    op.drop_column('health_snapshots', 'l3_status')
    op.drop_column('health_snapshots', 'l2_status')
    op.drop_column('health_snapshots', 'l1_status')
    op.drop_column('health_snapshots', 'score_details')
    op.drop_column('health_snapshots', 'score')
    op.drop_column('health_snapshots', 'agent_name')
    op.drop_index(op.f('ix_health_events_created_at'), table_name='health_events')
    op.drop_index(op.f('ix_health_events_agent_id'), table_name='health_events')
    op.add_column('health_check_runs', sa.Column('check_level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('health_check_runs', sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('health_check_runs', 'checked_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('health_check_runs', 'status',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('health_check_runs', 'agent_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.drop_column('health_check_runs', 'error_message')
    op.drop_column('health_check_runs', 'latency_ms')
    op.drop_column('health_check_runs', 'level')
    op.drop_column('health_check_runs', 'agent_name')
    op.drop_index(op.f('ix_heal_rules_agent_id'), table_name='heal_rules')
    op.add_column('encryption_keys', sa.Column('key_material', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('encryption_keys', sa.Column('key_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # 注：uq_encryption_keys_key_name 已存在于DB（无未命名约束），无需 drop/recreate
    op.alter_column('encryption_keys', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('encryption_keys', 'note')
    op.drop_column('encryption_keys', 'retired_at')
    op.drop_column('encryption_keys', 'status')
    op.drop_column('encryption_keys', 'key_id')
    op.drop_index(op.f('ix_dialogue_ratings_conversation_id'), table_name='dialogue_ratings')
    op.create_index(op.f('ix_conversations_user_id_updated_at'), 'conversations', ['user_id', 'updated_at'], unique=False)
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_index(op.f('ix_conversations_agent_id_user_id'), 'conversations', ['agent_id', 'user_id'], unique=False)
    op.drop_index(op.f('ix_component_scan_items_scan_id'), table_name='component_scan_items')
    op.drop_index(op.f('ix_component_scan_items_component_type'), table_name='component_scan_items')
    op.add_column('collaboration_tasks', sa.Column('workspace_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('collaboration_tasks', sa.Column('mode', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('collaboration_tasks', sa.Column('result_json', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('collaboration_tasks', sa.Column('goal', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('collaboration_tasks', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('collaboration_tasks', sa.Column('progress', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('collaboration_tasks', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('collaboration_tasks', sa.Column('created_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('collaboration_tasks', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('collaboration_tasks', sa.Column('config_json', sa.TEXT(), autoincrement=False, nullable=True))
    # 注：collaboration_tasks 无未命名外键/约束，drop(None) 为自动生成残留，跳过
    op.drop_index(op.f('ix_collaboration_tasks_collaboration_id'), table_name='collaboration_tasks')
    op.create_index(op.f('ix_collaboration_tasks_workspace_id'), 'collaboration_tasks', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_collaboration_tasks_status'), 'collaboration_tasks', ['status'], unique=False)
    op.alter_column('collaboration_tasks', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('collaboration_tasks', 'completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('collaboration_tasks', 'started_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('collaboration_tasks', 'error_message')
    op.drop_column('collaboration_tasks', 'output_text')
    op.drop_column('collaboration_tasks', 'input_text')
    op.drop_column('collaboration_tasks', 'role')
    op.drop_column('collaboration_tasks', 'order')
    op.drop_column('collaboration_tasks', 'agent_name')
    op.drop_column('collaboration_tasks', 'agent_id')
    op.drop_column('collaboration_tasks', 'collaboration_id')
    op.drop_index(op.f('ix_batch_install_items_queue_id'), table_name='batch_install_items')
    op.add_column('backup_records', sa.Column('workspace_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('backup_records', sa.Column('included_components', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('backup_records', sa.Column('encrypted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('backup_records', sa.Column('checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('backup_records', sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_backup_records_agent_id'), table_name='backup_records')
    op.create_index(op.f('ix_backup_records_workspace_id'), 'backup_records', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_backup_records_status'), 'backup_records', ['status'], unique=False)
    op.alter_column('backup_records', 'completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('backup_records', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('backup_records', 'size_bytes',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('backup_records', 'file_path',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    op.alter_column('backup_records', 'status',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'running'::character varying"))
    op.alter_column('backup_records', 'backup_type',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('backup_records', 'is_deleted')
    op.drop_column('backup_records', 'created_by')
    op.drop_column('backup_records', 'error_message')
    op.drop_column('backup_records', 'duration_seconds')
    op.drop_column('backup_records', 'retained_until')
    op.drop_column('backup_records', 'data_stats')
    op.drop_column('backup_records', 'key_id')
    op.drop_column('backup_records', 'encryption_algo')
    op.drop_column('backup_records', 'checksum_sha256')
    op.drop_column('backup_records', 'base_backup_id')
    op.drop_column('backup_records', 'scope')
    op.drop_column('backup_records', 'agent_name')
    op.drop_column('backup_records', 'agent_id')
    op.add_column('backup_policies', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('backup_policies', sa.Column('components', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('backup_policies', sa.Column('schedule', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('backup_policies', sa.Column('workspace_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_backup_policies_agent_id'), table_name='backup_policies')
    op.alter_column('backup_policies', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('backup_policies', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('backup_policies', 'default_scope')
    op.drop_column('backup_policies', 'drill_cron')
    op.drop_column('backup_policies', 'drill_enabled')
    op.drop_column('backup_policies', 'retention_incremental_count')
    op.drop_column('backup_policies', 'retention_full_count')
    op.drop_column('backup_policies', 'encryption_enabled')
    op.drop_column('backup_policies', 'event_types')
    op.drop_column('backup_policies', 'event_trigger_enabled')
    op.drop_column('backup_policies', 'incremental_interval_hours')
    op.drop_column('backup_policies', 'full_backup_cron')
    op.drop_column('backup_policies', 'agent_name')
    op.drop_column('backup_policies', 'agent_id')
    op.drop_index(op.f('ix_backup_event_logs_agent_id'), table_name='backup_event_logs')
    op.add_column('audit_rules', sa.Column('condition', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('audit_rules', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('audit_rules', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_audit_rules_rule_type'), table_name='audit_rules')
    op.alter_column('audit_rules', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('audit_rules', 'severity')
    op.drop_column('audit_rules', 'params')
    op.drop_column('audit_rules', 'rule_name')
    op.add_column('audit_logs', sa.Column('resource_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('workspace_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('user_agent', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('detail', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('action', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('agent_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('resource_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_result'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_partition_date'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_operator_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_category'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_type'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_workspace_id'), 'audit_logs', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id_action'), 'audit_logs', ['user_id', 'action'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_recorded_at'), 'audit_logs', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.alter_column('audit_logs', 'curr_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('audit_logs', 'created_at')
    op.drop_column('audit_logs', 'verified')
    op.drop_column('audit_logs', 'partition_date')
    op.drop_column('audit_logs', 'trace_id')
    op.drop_column('audit_logs', 'failure_reason')
    op.drop_column('audit_logs', 'result')
    op.drop_column('audit_logs', 'details')
    op.drop_column('audit_logs', 'target_id')
    op.drop_column('audit_logs', 'action_type')
    op.drop_column('audit_logs', 'category')
    op.drop_column('audit_logs', 'device_info')
    op.drop_column('audit_logs', 'operator_ip')
    op.drop_column('audit_logs', 'operator_name')
    op.drop_column('audit_logs', 'operator_id')
    op.drop_column('audit_logs', 'timestamp')
    op.add_column('audit_archives', sa.Column('original_log_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('audit_archives', sa.Column('archive_size_bytes', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('audit_archives', sa.Column('checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('audit_archives', sa.Column('archive_date', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_audit_archives_archive_key'), table_name='audit_archives')
    op.alter_column('audit_archives', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_archives', 'archive_path',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('audit_archives', 'record_count')
    op.drop_column('audit_archives', 'end_date')
    op.drop_column('audit_archives', 'start_date')
    op.drop_column('audit_archives', 'archive_key')
    op.drop_index(op.f('ix_audit_alerts_operator_id'), table_name='audit_alerts')
    op.drop_index(op.f('ix_audit_alerts_created_at'), table_name='audit_alerts')
    op.drop_index(op.f('ix_audit_alerts_alert_type'), table_name='audit_alerts')
    op.drop_index(op.f('ix_alert_records_fired_at'), table_name='alert_records')
    op.drop_index(op.f('ix_alert_records_config_id'), table_name='alert_records')
    op.drop_index(op.f('ix_alert_records_agent_id'), table_name='alert_records')
    op.create_index(op.f('ix_agents_workspace_id_status'), 'agents', ['workspace_id', 'status'], unique=False)
    op.create_index(op.f('ix_agents_model_provider'), 'agents', ['model_provider'], unique=False)
    op.create_index(op.f('ix_agents_created_by_status'), 'agents', ['created_by', 'status'], unique=False)
    op.create_index(op.f('ix_agents_created_at'), 'agents', ['created_at'], unique=False)
    op.drop_column('agents', 'webhook_url')
    op.drop_index(op.f('ix_agent_metrics_recorded_at'), table_name='agent_metrics')
    op.drop_index(op.f('ix_agent_metrics_agent_id'), table_name='agent_metrics')
    op.add_column('agent_health_configs', sa.Column('alert_threshold', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'60'::double precision"), autoincrement=False, nullable=True))
    op.add_column('agent_health_configs', sa.Column('check_interval_minutes', sa.INTEGER(), server_default=sa.text('5'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_agent_health_configs_agent_id'), table_name='agent_health_configs')
    op.create_unique_constraint(op.f('uq_agent_health_configs_agent_id'), 'agent_health_configs', ['agent_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('agent_health_configs', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('agent_health_configs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_health_configs', 'agent_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.drop_column('agent_health_configs', 'auto_restart_on_l1_fail')
    op.drop_column('agent_health_configs', 'l4_test_prompt')
    op.drop_column('agent_health_configs', 'l3_model_id')
    op.drop_column('agent_health_configs', 'l3_mcp_servers')
    op.drop_column('agent_health_configs', 'l3_skills')
    op.drop_column('agent_health_configs', 'process_name')
    op.drop_column('agent_health_configs', 'pid')
    op.drop_column('agent_health_configs', 'ready_endpoint')
    op.drop_column('agent_health_configs', 'l4_interval_sec')
    op.drop_column('agent_health_configs', 'l3_interval_sec')
    op.drop_column('agent_health_configs', 'l2_interval_sec')
    op.drop_column('agent_health_configs', 'l1_interval_sec')
    op.create_table('collaboration_agents',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('agent_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('collaboration_agents_pkey'))
    )
    op.create_index(op.f('ix_collaboration_agents_task_id'), 'collaboration_agents', ['task_id'], unique=False)
    # ### end Alembic commands ###
